name: flutter_blue_max_darwin
description: iOS and macOS implementation of the flutter_blue_max plugin.
version: 5.0.1
homepage: https://github.com/phntmxyz/flutter_blue_max

environment:
  sdk: ^3.0.0
  flutter: '>=3.7.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_blue_max_platform_interface: 5.0.0

# uncomment for platform interface local development
dependency_overrides:
  flutter_blue_max_platform_interface:
    path: ../flutter_blue_max_platform_interface

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    implements: flutter_blue_max
    platforms:
      ios:
        pluginClass: FlutterBlueMaxPlugin
        dartPluginClass: FlutterBlueMaxDarwin
        sharedDarwinSource: true
      macos:
        pluginClass: FlutterBlueMaxPlugin
        dartPluginClass: FlutterBlueMaxDarwin
        sharedDarwinSource: true
