name: flutter_blue_max
description: Flutter plugin for connecting and communicating with Bluetooth Low Energy devices.
version: 1.35.10
homepage: https://github.com/phntmxyz/flutter_blue_max

environment:
  sdk: ^3.0.0
  flutter: '>=3.7.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_blue_max_platform_interface: 5.0.0
  flutter_blue_max_android: 5.0.3
  flutter_blue_max_darwin: 5.0.1
  flutter_blue_max_linux: 5.0.0
  flutter_blue_max_web: 5.0.1

dependency_overrides:
  flutter_blue_max_platform_interface:
    path: ../flutter_blue_max_platform_interface
  flutter_blue_max_android:
    path: ../flutter_blue_max_android
  flutter_blue_max_darwin:
    path: ../flutter_blue_max_darwin
  flutter_blue_max_linux:
    path: ../flutter_blue_max_linux
  flutter_blue_max_web:
    path: ../flutter_blue_max_web

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        default_package: flutter_blue_max_android
      ios:
        default_package: flutter_blue_max_darwin
      linux:
        default_package: flutter_blue_max_linux
      macos:
        default_package: flutter_blue_max_darwin
      web:
        default_package: flutter_blue_max_web
